apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-chat-backend
spec:
  selector:
    matchLabels:
      app: go-chat-backend
  replicas: 2
  template:
    metadata:
      labels:
        app: go-chat-backend
    spec:
      containers:
      - name: go-chat-backend
       image: chatApp-go-image-1.0
        ports:
        - name: http
          containerPort: 3023
        - name: tcp
          containerPort: 4445
        - name: ws
          containerPort: 2019