apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-chat-app
  labels:
    app: go-chat-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-chat-app
  template:
    metadata:
      labels:
        app: go-chat-app
    spec:
      containers:
      - name: go-chat-app
        image: animus123/go-chat-app:newest
        imagePullPolicy: Always
        ports:
        - containerPort: 3023
        env:
        - name: DB_HOST
          value: "postgres-service"
        - name: DB_PASSWORD
          value: "mysecretpassword"
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: "postgres"  
        - name: DB_NAME
          value: "userinfo"      
---

apiVersion: v1
kind: Service
metadata:
  name: go-chat-app
spec:
  type: NodePort
  selector:
    app : go-chat-app
  ports:
    - protocol: TCP
      port: 3023
      targetPort: 3023
      nodePort: 30029
